name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Install dependencies
        run: yarn
  
      - name: Build and package
        run: yarn package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "*.vsix"
          retention-days: 10
