on:
  workflow_call:
    secrets:
      OPEN_VSX_TOKEN:
        required: false
      VS_MARKETPLACE_TOKEN:
        required: false

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Publish to Open VSX Registry
        if: ${{ secrets.OPEN_VSX_TOKEN }}
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        if: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
